Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> I still have the problem to create a change reference.
> Is there something remained to set up for this repo?
> 
> =======================
> git push origin HEAD:refs/master
> Enumerating objects: 71, done.
> Counting objects: 100% (71/71), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (63/63), done.
> Writing objects: 100% (69/69), 13.46 KiB | 1.92 MiB/s, done.
> Total 69 (delta 12), reused 0 (delta 0)
> remote: Resolving deltas: 100% (12/12)
> remote: error: branch refs/master:
> remote: You need 'Create' rights to create new references.
> remote: User: YoonsoonJahng
> remote: Contact an administrator to fix the permissions
> remote: Processing changes: refs: 1, done
> To ssh://gerrit.onap.org:29418/integration/terraform
>  ! [remote rejected] HEAD -> refs/master (prohibited by Gerrit: not permitted: create)
> error: failed to push some refs to 'ssh://YoonsoonJahng@gerrit.onap.org:29418/integration/terraform'

You have a typo in the git reference name, it's "refs/for/master", not "refs/master", so the complete push command should look like:

git push origin HEAD:refs/for/master

Patch-set: 1